//POST: /api/v1/chapters/:chapters
//get chapter detail
//teacher, learners of this course, admin, root
###
GET http://localhost:5000/api/v1/chapters/css-la-gi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0MTEzNjIsImV4cCI6MTYzNzQxODU2Mn0.HDbW2G9OKrQRL54oHDNV01Nu3Q1YON_5IrzVPQ20-NY

//POST: /api/v1/chapters
//teacher required
###
POST http://localhost:5000/api/v1/chapters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0MDAyMDksImV4cCI6MTYzNzQwNzQwOX0.kktsaQu6LFQmIovJTaarxS4rBgeHMqnbRAS6tlcN6qE

{
  "courseId": "617628e7a710327b33ddb813",
  "number": 4,
  "title": "SCSS vs CSS",
  "description": "SCSS vs CSS"
}

//PUT: /api/v1/chapters
//teacher required
###
PUT http://localhost:5000/api/v1/chapters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0MDAyMDksImV4cCI6MTYzNzQwNzQwOX0.kktsaQu6LFQmIovJTaarxS4rBgeHMqnbRAS6tlcN6qE

{
  "id": "6198c3433738020f67466a77",
  "number": 3,
  "title": "SASS là gì?",
  "description": "SASS là gì?",
  "status": 1,
  "slug": "SASS"
}

//DELETE: /api/v1/chapters
//teacher required
###
DELETE http://localhost:5000/api/v1/chapters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0MDAyMDksImV4cCI6MTYzNzQwNzQwOX0.kktsaQu6LFQmIovJTaarxS4rBgeHMqnbRAS6tlcN6qE

{
  "id": "6198c6fa75a775188e82c4a1"
}