//GET: /api/v1/lessons/:lessonSlugOrId
//authentication require
###
GET http://localhost:5000/api/v1/lessons/619a3cd1a929586dfef0d408
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0OTY5NzIsImV4cCI6MTYzNzU4MzM3Mn0.TcH-vKKwgzkPeF13Q2RHTbfHVQH6dZd4hBh4T8WYUOE

//POST: /api/v1/lessons
//teacher required
###
POST http://localhost:5000/api/v1/lessons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzk5MjIzMTIsImV4cCI6MTYzOTkzNjcxMn0.J_SrRlf9YtyxAjahNLPbUe7zQX_DRmH8x7yIlLSGlLk

{
  "title": "Why this course?", 
  "description": "Why this course is important?", 
  "chapterId": "61bdb98d781ae14c821bd2f7",
  "url":"https://i.vimeocdn.com/video/1260168573-3e0824e5e185677f821d73e506ccb839285755d85009d8cad?mw=2200&mh=1238&q=70"
}

//PUT: /api/v1/lessons/:id
//teacher required
###
PUT http://localhost:5000/api/v1/lessons/61bf3aab90f2681ee2370016
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzk5MjIzMTIsImV4cCI6MTYzOTkzNjcxMn0.J_SrRlf9YtyxAjahNLPbUe7zQX_DRmH8x7yIlLSGlLk

{
  "description": "Why this course is important?", 
  "url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4"
}

//DELETE: /api/v1/lessons/:id
//teacher required
###
DELETE http://localhost:5000/api/v1/lessons/619a4198dc1cebdd3c70f4c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0OTY5NzIsImV4cCI6MTYzNzU4MzM3Mn0.TcH-vKKwgzkPeF13Q2RHTbfHVQH6dZd4hBh4T8WYUOE
