//GET: /api/v1/lessons/:lessonSlugOrId
//authentication require
###
GET http://localhost:5000/api/v1/lessons/619a3cd1a929586dfef0d408
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0OTY5NzIsImV4cCI6MTYzNzU4MzM3Mn0.TcH-vKKwgzkPeF13Q2RHTbfHVQH6dZd4hBh4T8WYUOE

//POST: /api/v1/lessons
//teacher required
###
POST http://localhost:5000/api/v1/lessons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0OTY5NzIsImV4cCI6MTYzNzU4MzM3Mn0.TcH-vKKwgzkPeF13Q2RHTbfHVQH6dZd4hBh4T8WYUOE

{
  "title": "Lesson 5", 
  "description": "Introduce 3", 
  "chapterId": "6198c31c3738020f67466a69"
}

//PUT: /api/v1/lessons/:id
//teacher required
###
PUT http://localhost:5000/api/v1/lessons/61b61640f7b4f47d2f9a13b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzk4MDE1NTMsImV4cCI6MTYzOTgxNTk1M30.PCcfNMBh07uyjxeJ14bFclE47VVVM8Bn-3AnqACtAtQ

{
  "description": "Introduce 34213"
}

//DELETE: /api/v1/lessons/:id
//teacher required
###
DELETE http://localhost:5000/api/v1/lessons/619a4198dc1cebdd3c70f4c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2Mzc0OTY5NzIsImV4cCI6MTYzNzU4MzM3Mn0.TcH-vKKwgzkPeF13Q2RHTbfHVQH6dZd4hBh4T8WYUOE
