//GET: /api/v1/users/all-info
//Authentication
//get all information of user
###
GET http://localhost:5000/api/v1/users/all-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXIyQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDYwNTZlNzJlNGM5Yjc2MDI5NTYwNSIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MywibmFtZSI6InRlYWNoZXIifSwiZmlyc3ROYW1lIjoiUXVhbmcgSHV5IiwibGFzdE5hbWUiOiJEYW5nIiwiaWF0IjoxNjM4NTQ0NTE5LCJleHAiOjE2Mzg1NTg5MTl9.bTc9rY5fpVa8yh77vm110lCh1FfHtPLpqqzYilD39Ko

//GET: /api/v1/users/profile
//Authentication
//get profile info only
###
GET http://localhost:5000/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJmaXJzdE5hbWUiOiJ0b25pIiwibGFzdE5hbWUiOiJkZXYiLCJpYXQiOjE2MzgwOTM1OTAsImV4cCI6MTYzODEwNzk5MH0.B5elC70hWq35f7oKu4p6kVj3_W9MMd6JRDCop2PImPU

//GET: /api/v1/users/:userId/profile
//public
//get user profile public
###
GET http://localhost:5000/api/v1/users/6146054c72e4c9b7602955ff/profile

//GET: /api/v1/users/teaching-courses
//authentication require
//get teaching-courses only
###
GET http://localhost:5000/api/v1/users/teaching-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE1YzlkY2ZhMDk0NzY1OGU2M2JlMWZiIiwic3RhdHVzIjoyLCJyb2xlIjp7ImlkIjozLCJuYW1lIjoidGVhY2hlciJ9LCJpYXQiOjE2MzM4NTQyMTEsImV4cCI6MTYzMzg2MTQxMX0.irmtpRU_Or6e5a3e7gQhTiOqwv_V0R89h-ck2k50kro

//GET: /api/v1/users/learning-courses
//authentication require
//get learning-courses only
###
GET http://localhost:5000/api/v1/users/learning-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlYXJuZXIyQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNjFhNzUwNDhkY2MxNzk0MWI4ZTZlZiIsInN0YXR1cyI6Miwicm9sZSI6eyJpZCI6MywibmFtZSI6InRlYWNoZXIifSwiaWF0IjoxNjMzODU2MDAxLCJleHAiOjE2MzM4NjMyMDF9.iGrgBGf6Knq9vUkt-Xl0avWidLPxk4ewvWsqp7k3UaI

//GET: /api/v1/users/notifications
//authentication require
//get notifications only
###
GET http://localhost:5000/api/v1/users/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlYXJuZXIyQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNjFhNzUwNDhkY2MxNzk0MWI4ZTZlZiIsInN0YXR1cyI6Miwicm9sZSI6eyJpZCI6MywibmFtZSI6InRlYWNoZXIifSwiaWF0IjoxNjMzODU2MDAxLCJleHAiOjE2MzM4NjMyMDF9.iGrgBGf6Knq9vUkt-Xl0avWidLPxk4ewvWsqp7k3UaI

//PUT: /api/v1/users/profile
//authentication required
//update user profile
###
PUT http://localhost:5000/api/v1/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlYXJuZXJAZ21haWwuY29tIiwidXNlcklkIjoiNjE0YjM2NjZiMTBkYmE0NzNjNzM2NjkyIiwic3RhdHVzIjoxLCJyb2xlIjp7ImlkIjoyLCJuYW1lIjoibGVhcm5lciJ9LCJpYXQiOjE2MzUwMDE3NzQsImV4cCI6MTYzNTAwODk3NH0.INyA2w99xOFiV917nhKe9zjoVpkemWZdTX_LCh7D968

{
  "firstName": "D",
  "lastName": "Nguyen",
  "dateOfBirth": "3/15/1999",
  "socialLinks": {
    "twitter": "http://twitter.com/abc"
  },
  "phoneNumber": "0779440161"
}

//PUT: /api/v1/change-password
//authentication required
//change user password
###
PUT http://localhost:5000/api/v1/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxlYXJuZXIyQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNjFhNzUwNDhkY2MxNzk0MWI4ZTZlZiIsInN0YXR1cyI6Miwicm9sZSI6eyJpZCI6MywibmFtZSI6InRlYWNoZXIifSwiaWF0IjoxNjMzODY4OTYwLCJleHAiOjE2MzM4NzYxNjB9.grTDw2VB_56Jdl02rK5FCZtJ469gPgvfmexDL79TXfc

{
  "oldPassword": "12345",
  "newPassword": "123456"
}

###
GET http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzg2MjkwOTMsImV4cCI6MTYzODY0MzQ5M30.4PJzYrjplZx0A7ryXRSl3UqA_4FsETwMN3DNjcjdWFk

//Post new user from admin
###
POST http://localhost:5000/api/v1/admin/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzg2MjkwOTMsImV4cCI6MTYzODY0MzQ5M30.4PJzYrjplZx0A7ryXRSl3UqA_4FsETwMN3DNjcjdWFk

{
  //"userId": "",
  "email": "abc@gmail.com",
  "firstName": "A",
  "lastName": "Nguyen",
  "dateOfBirth": "3/15/1999",
  "description": "Test",
  "status": 1,
  "phoneNumber": "0783465975",
  "role": 2,
  //socialLinks: {facebook: String, instagram: String, linkedIn: String, github: String, twitter: String}
  "socialLinks": {
    "facebook": "http://facebook.com/abc",
    "instagram": "http://instagram.com/abc",
    "linkedIn": "http://linkedin.com/abc",
    "github": null,
    "twitter": null
  },
  //address: {street: String, city: String, country: String}
  "address": {
    "street": "123",
    "city": "Hanoi",
    "country": "Vietnam"
  },
  "newPassword": "123456",
  "imageUrl": ""
}

//Post new user from admin
###
POST http://localhost:5000/api/v1/admin/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzg2MjkwOTMsImV4cCI6MTYzODY0MzQ5M30.4PJzYrjplZx0A7ryXRSl3UqA_4FsETwMN3DNjcjdWFk

{
  "userId": "61ab8591e02b3b3f33f9f27b",
  //"email": "abc@gmail.com",
  "firstName": "B",
  "lastName": "Nguyen",
  "dateOfBirth": "5/15/1999",
  "description": "Test 123",
  "status": 2,
  "phoneNumber": "0783465975",
  "role": 1,
  //socialLinks: {facebook: String, instagram: String, linkedIn: String, github: String, twitter: String}
  "socialLinks": {
    "facebook": "http://facebook.com/abc",
    "instagram": null,
    "linkedIn": "http://linkedin.com/abc",
    "github": null,
    "twitter": null
  },
  //address: {street: String, city: String, country: String}
  "address": {
    "street": "12345",
    "city": "Hanoi",
    "country": "Vietnam"
  },
  "newPassword": "123456",
  "imageUrl": ""
}

###
POST http://localhost:5000/api/v1/admin/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYxNDc1YWY4MzAxZjdiYTNlMWM2N2E2YiIsInN0YXR1cyI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6ImFkbWluIn0sImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJOZ3V5ZW4iLCJpYXQiOjE2Mzg2MjkwOTMsImV4cCI6MTYzODY0MzQ5M30.4PJzYrjplZx0A7ryXRSl3UqA_4FsETwMN3DNjcjdWFk

{
  "userId": "61ab8591e02b3b3f33f9f27b",
  "newPassword": "123456"
}